package com.example.stockapp.data.mapper

import com.example.stockapp.data.local.CompanyListingEntity
import com.example.stockapp.data.remote.dto.CompanyInfoDto
import com.example.stockapp.domain.model.CompanyInfo
import com.example.stockapp.domain.model.CompanyListing
import com.google.common.truth.Truth.assertThat
import org.junit.Test

class CompanyMapperTest {

    val companyListing = CompanyListing("Agilent Technologies Inc", "A", "NYSE")
    val companyListingEntity = CompanyListingEntity("Agilent Technologies Inc", "A", "NYSE", null)
    val companyInfoDto = CompanyInfoDto(
        "IBM",
        "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        "International Business Machines",
        "USA",
        "COMPUTER & OFFICE EQUIPMENT"
        )
    val companyInfo = CompanyInfo(
        "IBM",
        "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
        "International Business Machines",
        "USA",
        "COMPUTER & OFFICE EQUIPMENT"
    )



    @Test
    fun `Convert CompanyListEntity to CompanyListing`() {
        val result = companyListingEntity.toCompanyListing()

        assertThat(result).isEqualTo(companyListing)
    }

    @Test
    fun `Convert CompanyListing to CompanyListEntity`() {
        val result =  companyListing.toCompanyListingEntity()

        assertThat(result).isEqualTo(companyListingEntity)
    }

    @Test
    fun `Convert CompanyInfoDto to CompanyInfo`() {
        val result = companyInfoDto.toCompanyInfo()

        assertThat(result).isEqualTo(companyInfo)
    }

}